<a href="https://colab.research.google.com/github/sakshimohite8/ML_Practicals_MCA/blob/main/05_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

In [15]:
data = pd.read_csv("/content/car data.csv")
data.columns = data.columns.str.strip()
print(data.columns.tolist())

['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Kms_Driven', 'Fuel_Type', 'Seller_Type', 'Transmission', 'Owner']

In [19]:
X = data[["Year", "Present_Price", "Kms_Driven", "Fuel_Type", "Seller_Type", "Transmission", "Owner"]]
y = data["Selling_Price"]

In [20]:
print(X.head())

   Year  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0  2014           5.59       27000    Petrol      Dealer       Manual      0
1  2013           9.54       43000    Diesel      Dealer       Manual      0
2  2017           9.85        6900    Petrol      Dealer       Manual      0
3  2011           4.15        5200    Petrol      Dealer       Manual      0
4  2014           6.87       42450    Diesel      Dealer       Manual      0

In [21]:
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [22]:
data.tail()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
296,city,2016,9.50,11.6,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.9,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.0,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.5,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.9,5464,Petrol,Dealer,Manual,0

In [23]:
data.shape

(301, 9)

In [24]:
data.isnull()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
296,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False

In [25]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [26]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
296    False
297    False
298    False
299    False
300    False
Length: 301, dtype: bool

In [27]:
le = LabelEncoder()
data["Fuel_Type"] = le.fit_transform(data["Fuel_Type"])
data["Seller_Type"] = le.fit_transform(data["Seller_Type"])
data["Transmission"] = le.fit_transform(data["Transmission"])

In [28]:
X = data[[
    "Year",
    "Present_Price",
    "Kms_Driven",
    "Fuel_Type",
    "Seller_Type",
    "Transmission",
    "Owner"
]]

y = data["Selling_Price"]

In [29]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [30]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [31]:
y_pred = model.predict(X_test)
print(y_pred)

[ 2.96670467  8.3025584   6.05620758 -1.46814968  9.25713882  7.032306
  1.35164871  0.8268692   1.37173108  7.10742891  8.74382695  0.58613312
  8.50347194  3.42803571  6.50183791  3.08701389  0.46323861 10.8959559
  1.76487652  2.36736645  0.37538646  7.73247978  6.2075281   2.64722707
  0.78232086  3.72073841  5.33393873  2.83824054  2.16090172  1.77220708
  0.37859447  8.79078642 -0.7007019   2.2988819   8.21516023  4.54037167
  7.35322104  7.6823757   2.91768184  8.08080852  3.99669454  4.34672417
  4.36388106  0.61018923  6.94478948  0.47281585  7.41596672 11.44059317
  3.14822313  4.95097368  6.86250813  2.19862524 20.53946595 16.79146986
  7.13952545  9.830903    4.49886186  8.62078376  1.810855    7.67299866
  0.21098592]

In [32]:
print("R2 Score:", r2_score(y_test, y_pred))
# Output: R2 Score: 0.846853957655803

R2 Score: 0.8468053957655803

In [33]:
prediction = model.predict([[2015, 5.5, 25000, 1, 0, 1, 0]])
print("Predicted Selling Price:", prediction[0])
# Output: Predicted Selling Price: 5.6225514669910425

Predicted Selling Price: 5.6226514660910425

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(